### PR TITLE
WIP Investment Performance

### PR DESCRIPTION
**Pull request by baartosz**
Hi. It's just a placeholder to let you know that I started working on Net Worth report.

### CODE REVIEW

**Comment by redstreet** [comment]
Great, thank you! I'll be happy to review the patch. Feel free to open an issue instead of an empty PR.

**Comment by baartosz** [comment]
I think now I have some grasp of what i'm working with and whats the goal. I pushed changes so you can see first steps i'm taking. 
Last commit added account split into value/internal/external. There is config to set these. I dont think regular expressions are useful here - i couldn't think of any value in excluding children accounts for example. List of full account names seems feasible - each group can have multiple and includes their sub-accounts.
image

**Comment by redstreet** [comment]
Cool! Nice to see this first pass working :).

A few suggestions:
- display current balance in output table
- output: I'd suggest two tables: one with just the four values (balance, contributions, reinvested-income, appreciation); and separate tables for the details for dividends, gains.

I'm also refining my thoughts on what this component should be about. More in a minute.

**Comment by redstreet** [comment]
@baartosz, let's clarify our thoughts around what this component should be about [here](https://github.com/redstreet/fava-investor/issues/26) first? What you are collecting and displaying seems to be in the right direction and valuable, but it made my rethink exactly what we want out of this component. I'd like to hear your thoughts too.

**Comment by redstreet** [comment]
I just ran this on my much larger beancount source. Here's what I saw:
- dividends is incorrect (dividends_total and dividends_withdrawn are almost equalto my contributions; I expect them to be less than 2 or 3%)
- diviends_reinvested is 3x what is should be
- gains_{unrealized, realized}: I'm not sure what these numbers are; but they are too big to be right.
- took > 1min to run on my 20k entry journal (not a problem for now)

I think the main problem is, it's quite a difficult problem to get right for the general case, which is what Martin also faced with the returns calculator.

Perhaps we can focus on getting things right one at a time: first focus on building an awesome dividends analyzer, then build an appreciation analyzer, then the contributions/withdrawals, and finally, the balance analyzier. What do you think? Anyway, before any of this, let's figure out what the proposal for this component should look like in the other thread.

**Comment by redstreet** [comment]
BTW, it's great to see that you're using and building on top of Martin's work in report.py. More work may be needed to get it right, but I definitely think this is the right call.

**Comment by baartosz** [comment]
I just tried to reuse account journal template from fava to display all entries involved in contribution calculation with changes they are doing. Seems like good debugging tool adding a lot of transparency.
image

**Comment by redstreet** [comment]
👍 on the journal, makes debugging very easy! And nice :)

Contributions seem to (incorrectly) include dividend reinvestments. There are two cases I see off the bat:
````
2010-01-01 * "dividend reinv"
  Assets:Investments 100 AAPL
  Assets:Investments -2000 USD

2010-01-01 * "dividend reinv"
  Assets:Investments 100 AAPL
  Income:Investments:Dividends -2000 USD
  Equity:Rounding-Errors 0.12 USD
````

Both cases get incorrectly included. My suspicion is, we'll run into more such cases. Here are my thoughts:

1. I'd still thinking it'd be easier starting with displaying just the balance across time in the roadmap in the other thread. This is very easy to verify, even against complex examples, just by running bean-query.

2. I'd recommend getting a more complex beancount file. Perhaps the example one in fava is complex enough? I think the beancount source includes a script to generate a complex, large example file.

Thoughts?

**Comment by redstreet** [comment]
It's also including sell transactions. Similar to case one above.

**Comment by baartosz** [comment]
Yes i certainly agree. I will close this PR for now and will create next one when i'll have one of the parts complete.

**Comment by redstreet** [comment]
Great, I look forward to it!

**Pull request closed without merging**
